name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install APT Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y ${{ matrix.compiler }} make tar wget
      - name: Install Premake and Generate Project Files
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta7/premake-5.0.0-beta7-linux.tar.gz
          tar -xf ./premake-5.0.0-beta7-linux.tar.gz
          ./premake5 --cc=${{ matrix.compiler }} gmake
      - name: Build Debug with ${{ matrix.compiler }}
        run: |
          make -j
